#!/bin/sh

kextload /Library/Extensions/FlockFlock.kext
CONSOLE_USER=$(ps aux | grep console | grep -v grep | cut -d' ' -f1)
sudo -u $CONSOLE_USER launchctl load /Library/LaunchAgents/com.zdziarski.FlockFlockUserAgent.plist
